
def gb_syn():
    return  [
            ['MT-CO1','cox1','COX1','COI','coi','cytochome oxidase 1','cytochome oxidase I',
             'cytochome oxidase subunit 1','cytochome oxidase subunit I',
             'cox I','coxI', 'cytochrome c oxidase subunit I'],
            ['MT-CO2','cox2','COX2','COII','coii','cytochome oxidase 2','cytochome oxidase II',
             'cytochome oxidase subunit 2','cytochome oxidase subunit II','cox II',
             'cytochrome c oxidase subunit II'],
            ['MT-CO3','cox3','COX3','COIII','coiii','cytochome oxidase 3',
             'cytochome oxidase III','cytochome oxidase subunit 3','cytochome oxidase subunit III'
             ,'cox III','cytochrome c oxidase subunit III'],
            ['18s','18S','SSU rRNA','18S ribosomal RNA','small subunit 18S ribosomal RNA', '18S rRNA'],
            ['28s','28S','LSU rRNA','28S ribosomal RNA','28S large subunit ribosomal RNA'],
            ['MT-ATP6','atp6','ATP6','atpase6','atpase 6','ATPase6','ATPASE6'],
            ['MT-ATP8','atp8','ATP8','atpase8','atpase 8','ATPase8','ATPASE8'],
            ['ATP9','atp9'],
            ['MT-CYB','cytochrome-b','cytb','CYTB','Cytb', 'cytochrome B','cytochrome b'],
            ['ef1a','Ef1a', 'elongation factor 1-alpha','elongation factor-1 alpha',
             'ef1-alpha','elongation factor 1 alpha'],
            ['MT-ND1','nd1','ND1','nadh1','NADH1','nadh 1','NADH 1',
             'NADH dehydrogenase subunit 1','NADH dehydrogenase subunit I','nad1','nadh1'],
            ['MT-ND2','nd2','ND2','nadh2','NADH2','nadh 2','NADH 2','NADH dehydrogenase subunit 2', 
             'NADH dehydrogenase subunit II','nad2','nadh2'],
            ['MT-ND3','nd3','ND3','nadh3','NADH3','nadh 3','NADH 3','NADH dehydrogenase subunit 3',
             'NADH dehydrogenase subunit III','nad3','nadh3'],
            ['MT-ND4','nd4','ND4','nadh4','NADH4','nadh 4','NADH 4','NADH dehydrogenase subunit 4',
             'NADH dehydrogenase subunit IV','nad4','nadh4'],
            ['MT-ND4L','nd4l','ND4L','nad4l','nadh4l', 'nadh4L', 'NADH dehydrogenase subunit 4l',
             'NADH dehydrogenase subunit 4L'],
            ['MT-ND5','nd5','ND5','nad5', 'nadh5','NADH5','nadh 5','NADH 5','NADH dehydrogenase subunit 5',
             'NADH dehydrogenase subunit V'],
            ['MT-ND6','nd6','ND6','nad6','nadh6','NADH6','nadh 6','NADH 6','NADH dehydrogenase subunit 6',
             'NADH dehydrogenase subunit VI'],
            ['rrnS','12srRNA','12s rRNA','12S ribosomal RNA','12S rRNA'],
            ['rrnL','16srRNA','16s rRNA','16S ribosomal RNA','16S rRNA'],
            ['C_mos', 'C-mos','c-mos','C-MOS'],
            ['GAPDH','gapdh'],
            ['RNApol2','RNApolII','RNA polymerase II']
            ]